joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    publish_stamped_twist: true
    frame: 'base_link'
    
    # Axis mappings
    axis_linear:
      x: 1                 # LEFTY
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 2               # RIGHTX
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 1.0

    # Button mappings
    require_enable_button: true
    enable_button: 6       # START
