/**:
  ros__parameters:
    mujoco_plugins:
      mujoco_3d_lidar_plugin:
        type: "mujoco_ros2_control_plugins/Mujoco3dLidarPlugin"
        lidar:
          frame_name: lidar_link_optical
          topic: /scan
      mujoco_camera_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 6.0
        camera:
          policy: streaming
          frame_name: camera_link_optical
          info_topic: /camera/camera_info
          image_topic: /camera/image
          depth_topic: /camera/depth_image
